### ISSUE TITLE
Folder scanning results in Internal Server Error

### ISSUE THREAD

**Issue by rwaffen** [bronko-media/bronko.media.server#281]
```
I, [2024-10-04T19:06:58.963956 #9]  INFO -- : Starting Folder Scan of: data/images/Stock/Memes
I, [2024-10-04T19:06:59.481844 #9]  INFO -- : Writing new Folders to DB ...
I, [2024-10-04T19:06:59.482281 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/
I, [2024-10-04T19:06:59.482505 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/years/
I, [2024-10-04T19:06:59.482533 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/years/2016/
I, [2024-10-04T19:06:59.482920 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/years/2017/
I, [2024-10-04T19:06:59.482940 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/years/2018/
I, [2024-10-04T19:06:59.482961 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/years/2019/
I, [2024-10-04T19:06:59.482977 #9]  INFO -- : Indexing Folder: data/images/Stock/Memes/years/2020/
2024-10-04 19:06:59 - NoMethodError - undefined method `clear_active_connections!' for class ActiveRecord::Base:
        Did you mean?  clear_validators!
        /bronko.media/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
        /bronko.media/lib/folders.rb:97:in `block in write_folders_to_db'
        /bronko.media/vendor/bundle/ruby/3.3.0/gems/parallel-1.26.3/lib/parallel.rb:650:in `call_with_index'
        /bronko.media/vendor/bundle/ruby/3.3.0/gems/parallel-1.26.3/lib/parallel.rb:441:in `block (2 levels) in work_in_threads'
        /bronko.media/vendor/bundle/ruby/3.3.0/gems/parallel-1.26.3/lib/parallel.rb:660:in `with_instrumentation'
        /bronko.media/vendor/bundle/ruby/3.3.0/gems/parallel-1.26.3/lib/parallel.rb:440:in `block in work_in_threads'
        /bronko.media/vendor/bundle/ruby/3.3.0/gems/parallel-1.26.3/lib/parallel.rb:219:in `block (4 levels) in in_threads'
192.168.178.94 - - [04/Oct/2024:19:06:59 +0200] "POST /folder/scan/6d1942ea046231620c068bddd900fa51 HTTP/1.1" 500 30 1.0258

```

**Comment by rwaffen** [comment]
> This method is deprecated or moved on the latest stable version.
